### ISSUE TITLE
FPU doesn't support unordered/ordered compare operations

### ISSUE THREAD

**Issue by stffrdhrn** [stffrdhrn/gcc#1]
It looks like we need to add an expand, and its not handled automatically.

Code
```
#include <stdio.h>
#include <math.h>

#ifndef NAN
#define NAN (0.0/0.0)
#endif

static void tstnan (void)
{
  double d;

  /* Various tests to detect a NaN without using the math library (-lm).
   * MIPSpro 7.3.1.3m (IRIX64) does too many optimisations, so that
   * both NAN != NAN and !(NAN >= 0.0 || NAN <= 0.0) give 0 instead
   * of 1. As a consequence, in MPFR, one needs to use
   *    #define DOUBLE_ISNAN(x) (!(((x) >= 0.0) + ((x) <= 0.0)))
   * in this case. */

  d = NAN;
  printf ("\n");
  printf ("NAN != NAN --> %d (should be 1)\n", d != d);
  printf ("isnan(NAN) --> %d (should be 1)\n", isnan (d));
  printf ("NAN >= 0.0 --> %d (should be 0)\n", d >= 0.0);
  printf ("NAN <= 0.0 --> %d (should be 0)\n", d <= 0.0);
  printf ("  #3||#4   --> %d (should be 0)\n", d >= 0.0 || d <= 0.0);
  printf ("!(#3||#4)  --> %d (should be 1)\n", !(d >= 0.0 || d <= 0.0));
  printf ("  #3 + #4  --> %d (should be 0)\n", (d >= 0.0) + (d <= 0.0));
  printf ("!(#3 + #4) --> %d (should be 1)\n", !((d >= 0.0) + (d <= 0.0)));
}

int main(char ** args)
{
  tstnan ();
}
```

Failure
```
$ or1k-elf-gcc -mdouble-float -mhard-float -mhard-div -mhard-mul -mcmov -msext -lm main.c 

main.c: In function 'tstnan':
main.c:29:1: error: unrecognizable insn:
   29 | }
      | ^
(insn 31 29 32 2 (set (reg:BI 34 ?sr_f)
        (unordered:BI (reg:DF 76)
            (reg:DF 77))) "main.c":22:3 -1
     (nil))
during RTL pass: vregs
main.c:29:1: internal compiler error: in extract_insn, at recog.c:2305
0x5e09ee _fatal_insn(char const*, rtx_def const*, char const*, int, char const*)
        ../../gcc/gcc/rtl-error.c:108

```

**Comment by bandvig** [comment]
Today I’ve tried to build NewLIB-based tool-chain. I used most recent sources for binutils (your binutils-gdb repo, branch orfpx64a32), GCC9 (your gcc repo, branch or1k-fpu-1) and NewLIB (sourceware repo, branch master).  I successfully build binutils and gcc stage-1. To build NewLIB I tried to use  `-msfimm -mshftimm -msext -mror -mcmov -mhard-mul -mhard-div -mhard-float -mdouble-float` options. And I got quite similar internal compiler errors:

../../../../../../newlib_20190328/newlib/libc/stdlib/strtod.c: In function 'strtof_l':
../../../../../../newlib_20190328/newlib/libc/stdlib/strtod.c:1299:1: error: unrecognizable insn:
 1299 | }
      | ^
(insn 21 20 22 2 (set (reg:BI 34 ?sr_f)
        (ordered:BI (reg/v:DF 48 [ val ])
            (reg/v:DF 48 [ val ]))) "../../../../../../newlib_20190328/newlib/libc/stdlib/strtod.c":1291:6 -1
     (nil))
during RTL pass: vregs
../../../../../../newlib_20190328/newlib/libc/stdlib/strtod.c:1299:1: internal compiler error: in extract_insn, at recog.c:2310


../../../../../../newlib_20190328/newlib/libc/stdio/vfprintf.c: In function '_vfprintf_r':
../../../../../../newlib_20190328/newlib/libc/stdio/vfprintf.c:1790:1: error: unrecognizable insn:
 1790 | }
      | ^
(insn 1030 1028 1031 129 (set (reg:BI 34 ?sr_f)
        (unle:BI (reg:DF 440)
            (reg:DF 443))) "../../../../../../newlib_20190328/newlib/libc/stdio/vfprintf.c":1229:8 -1
     (nil))
during RTL pass: vregs
../../../../../../newlib_20190328/newlib/libc/stdio/vfprintf.c:1790:1: internal compiler error: in extract_insn, at recog.c:2310

At the same time I could build NewLIB after options `-mhard-float -mdouble-float` were removed.

**Comment by stffrdhrn** [comment]
Thats interesting, I have not made any changes other than a rebase.  Perhaps the default fallbacks for `unordered` have become broken in underlying gcc.

**Comment by stffrdhrn** [comment]
Note, a workaround I have is to use `-O2` which usually optimizes out the unordered compares.

**Comment by stffrdhrn** [comment]
This seems related to https://gcc.gnu.org/bugzilla/show_bug.cgi?id=88055.

**Comment by bandvig** [comment]
Ah! I didn't mention, but I also used `-O2`. It couldn’t be overcome with optimization involving. The only solution for OR1K now is to remove `-mhard-float -mdouble-float` options from compiler’s command line. 
I read the link to GCC Bugzilla issue you mentioned above. If I understand correctly, there is no quick solution. 
Speaking about OR1K, I think we could implement unordered FP comparison. Btw, we have Richard’s proposal related to that (https://openrisc.io/proposals/lfsf). However, the proposal couldn’t be implemented as is without complete violation of backward compatibility. In fact bit [4] of FP opcode is already reserved to indicate `double` precision instruction.
I would propose to implement the following unordered FP comparison:

lf.sfun.s rA,rB  (opc: 0x2f)
lf.sfun.d rA,rB  (opc: 0x3f)
lf.sfueq.s rA,rB (opc: 0x28)
lf.sfueq.d rA,rB (opc: 0x38)
lf.sfult.s rA,rB (opc: 0x2C)
lf.sfult.d rA,rB (opc: 0x3C)
lf.sfule.s rA,rB (opc: 0x2D)
lf.sfule.d rA,rB (opc: 0x3D)

It is minimal set required by ISO C 99.
Additionally to keep symmetry with already implemented lf.sf* we also could implement NEQ/GT/GE:

lf.sfuneq.s rA,rB (opc: 0x29)
lf.sfuneq.d rA,rB (opc: 0x39)
lf.sfugt.s rA,rB (opc: 0x2A)
lf.sfugt.d rA,rB (opc: 0x3A)
lf.sfuge.s rA,rB (opc: 0x2B)
lf.sfuge.d rA,rB (opc: 0x3B)

I think I could make initial implementation in about one or two days.

**Comment by stffrdhrn** [comment]
Hi, the bug is mainly for fixing the compiler to support proper fallbacks.  I think the easiest way to do it is to just implement fallbacks in the OpenRISC GCC backend.  This is done in some other targets.

It would be neat to also support the unordered compares in hardware as well.

Also, it seems another workaround may be to add `-ffinite-math-only` which means unordered compares will not be generated.  This seems to work for me.

**Comment by stffrdhrn** [comment]
I think this patch fixes the issue where we don't support unordered compares.

@bandvig if you add support for unordered compares in hardware I can add to the toolchain.  Let me know if you want to get that in before I submit upstream.

We should also start working on updating the spec.

**Comment by bandvig** [comment]
I’ve created branch `https://github.com/openrisc/or1k_marocchino/tree/fp_unordered_cmp` with initial implementation of unordered comparison. All variants mentioned above and even more were implemented.
**Pay attention!**
**Opposite to my previous proposal, I changed opcode for lf.sfun.s(d). Now it is 0x2E (0x3E). I did that to keep DECODE logic which checks FPU instruction format validity.**
Resulting unordered comparison instructions summary:

lf.sfueq.s rA,rB (opc: 0x28)
lf.sfueq.d rA,rB (opc: 0x38)
lf.sfune.s rA,rB (opc: 0x29)
lf.sfune.d rA,rB (opc: 0x39)
lf.sfugt.s rA,rB (opc: 0x2A)
lf.sfugt.d rA,rB (opc: 0x3A)
lf.sfuge.s rA,rB (opc: 0x2B)
lf.sfuge.d rA,rB (opc: 0x3B)
lf.sfult.s rA,rB (opc: 0x2C)
lf.sfult.d rA,rB (opc: 0x3C)
lf.sfule.s rA,rB (opc: 0x2D)
lf.sfule.d rA,rB (opc: 0x3D)
lf.sfun.s rA,rB  (opc: 0x2E)
lf.sfun.d rA,rB  (opc: 0x3E)

Additionally I’ve added `fp_comparisons_table.odt` document into `doc/readme/` folder with description of all implemented FP comparison instructions and their relation to IEEE standard.
I haven’t tested them yet as there is no tool now. However you could start extending GCC port.

**Comment by bandvig** [comment]
> Also, it seems another workaround may be to add `-ffinite-math-only` which means unordered compares will not be generated. This seems to work for me.

I tried to add `-ffinite-math-only` to `-mhard-float -mdouble-float` and rebuild NewLIB. It failed again but in anpther place.

../../../../../../newlib_20190328/newlib/libm/complex/cacosh.c: In function 'cacosh':
../../../../../../newlib_20190328/newlib/libm/complex/cacosh.c:93:1: error: unrecognizable insn:
   93 | }
      | ^
(insn 89 88 90 2 (set (reg:BI 34 ?sr_f)
        (ordered:BI (reg:DF 66 [ _28 ])
            (reg:DF 67 [ _29 ]))) -1
     (nil))
during RTL pass: vregs
../../../../../../newlib_20190328/newlib/libm/complex/cacosh.c:93:1: internal compiler error: in extract_insn, at recog.c:2310

During next days I'll try your freshest commit.

**Comment by stffrdhrn** [comment]
This seems fixed as per commit mentioned. Additional work in progress to add unordered compares to the hardware spec.  

https://lists.librecores.org/pipermail/openrisc/2019-April/001969.html
