### ISSUE TITLE
Fail building NewLIB with Spec 1.3 GCC9

### ISSUE THREAD

**Issue by bandvig** [stffrdhrn/gcc#5]
As I mentioned in another discussion I build binutils and GCC (stage-1) from yours branches which follow spec-1.3 and I got error while building NewLIB with options `-mhard-float -mdouble-float` (they are not present in command line because they are pre compiled at gcc of stage-1 build). Here the error message:
```
or1k-elf-gcc -B/home/BAndViG/ORPSoC/swlib/_bld_gcc9_spec13/newlib/or1k-elf/newlib/ -isystem /home/BAndViG/ORPSoC/swlib/_bld_gcc9_spec13/newlib/or1k-elf/newlib/targ-include -isystem /home/BAndViG/ORPSoC/swlib/newlib_20190328/newlib/libc/include -B/home/BAndViG/ORPSoC/swlib/_bld_gcc9_spec13/newlib/or1k-elf/libgloss/or1k -L/home/BAndViG/ORPSoC/swlib/_bld_gcc9_spec13/newlib/or1k-elf/libgloss/libnosys -L/home/BAndViG/ORPSoC/swlib/newlib_20190328/libgloss/or1k    -DPACKAGE_NAME=\"newlib\" -DPACKAGE_TARNAME=\"newlib\" -DPACKAGE_VERSION=\"3.1.0\" -DPACKAGE_STRING=\"newlib\ 3.1.0\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -I. -I../../../../../../newlib_20190328/newlib/libm/math -I../../../../../../newlib_20190328/newlib/libm/math/../common -fno-builtin -O2 -DREENTRANT_SYSCALLS_PROVIDED      -g -O2 -c -o lib_a-s_erf.o `test -f 's_erf.c' || echo '../../../../../../newlib_20190328/newlib/libm/math/'`s_erf.c
/tmp/cclmLocx.s: Assembler messages:
/tmp/cclmLocx.s:871: Error: Invalid register pair, offset not 1 or 2. `lf.sub.d r25,r27,r25,r27,r31,r16'
```

**Comment by stffrdhrn** [comment]
Let me have a look, I can see what is happening, but this kind of code should not be generated.  GCC should no not to put a double starting `r31`.

**Comment by stffrdhrn** [comment]
I pushed a fix for this.  I am guessing this was a problem before and doubles were getting base register as `r31` but we just didn't notice it as we didn't run the code.  We notice now because I added assembler verification for it.  Now GCC should not allocate doubles to start at `r0`, `r30` or `r31`.  

`r0` because we don't guarantee `r1` or `r2` will also be zero.  (`r0` is allowed by the assembler and should be find for the CPU, but it doesn't really make much sense.) 

`r30` and `r31`, should probably be validated in the CPU and cause illegal instruction exceptions if the pair register is an overflow.  Is that done now?  What do you think about checking for that?

**Comment by bandvig** [comment]
@stffrdhrn 

> `r30` and `r31`, should probably be validated in the CPU and cause illegal instruction exceptions if the pair register is an overflow. Is that done now? What do you think about checking for that?

It isn't implemented now. It could be useful even so it increases DECODE logic. I'm going to implement it in `fp_unordered_cmp` branch. Additionally I'm going to open OPTION_ORFPX64A32_ABI as "GCC9" in the branch as it targeted for gathering all spec-1.3 modifications.

Also I'll rebuild GCC with the fix during next two days and try it on pipe updated with additionally FP64 operands boundary check.

**Comment by bandvig** [comment]
I’ve updated `fp_unordered_cmp` branch with boundary checks for FP64- instruction’s A1/B1/D1 addresses. Also OPTION_ORFPX64A32_ABI was opened as `GCC9`. And multiplexers for A2/B2/D2 computation were replaced by adders with carry input. Even so I didn’t tested that (just lints by verilator), I think you could simulate it with a program build by your GCC9.
Unfortunately, I made mistake building GCC stage-1.  That means I’ll get new tool chain in two days as minimum. Because I could build on evenings only and each gcc build takes about 2 hours on my PC.

**Comment by bandvig** [comment]
OK. I complete building tool-chain than build Whetstone and run it successfully on MAROCCHINO from fp_unordered_cmp branch.
