### ISSUE TITLE
which branch is ported to gcc-6 ?

### ISSUE THREAD

**Issue by zhijianli88** [stffrdhrn/gcc#8]
Looks the master is align with gcc mainline, and there are some many branches on your repo, is there any gcc-6 supported branch ?

**Comment by stffrdhrn** [comment]
There is gcc 5 and gcc 7 but it's for the old non-fsf non-gnu port.  They are not supported.
See https://github.com/openrisc/or1k-gcc/branches

Branches or1k-7.2.0. And or1k-5.4.0.  These are no longer supported.

It should be fairly easy to backport this to 6 tough.  Why can't you use gcc9?

**Comment by stffrdhrn** [comment]
Closing as no updates for ~1 year.
